import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="container">
          <div className="flex flex-row">
            <div className="bg-gray-900 basis-1/6"></div>
            <div className="bg-gray-300 basis-5/6 text-black">
              <div className="p-2">{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
